### ISSUE TITLE
the GI is Flickering if multiple cameras exist in the scene

### ISSUE THREAD

**Issue by Shandy666** [jiaozi158/UnitySSGIURP#11]
Im using Deferred rendering and vulkan, and I'm trying to make mirror effect using Render texture and A camera, but the GI is Flickering, I have tried to disable depth texture, opaque texture, and post processing in that reflection camera, but it doesn't help, any solution for this?

Thanks in Advance

**Comment by jiaozi158** [comment]
Hi, which version of Unity are you using?

You can try disabling SSGI on the reflection camera as a temporary solution, and I'll look into this later. (currently a bit busy)

**Comment by Shandy666** [comment]
@jiaozi158 thanks for the response, I'm using unity 2022.3.46f1,

And how could I disable the SSGI on the reflection camera? I've tried to disable the post-processing by the way, but it still the same.

**Comment by jiaozi158** [comment]
> thanks for the response, I'm using unity 2022.3.46f1,

Thank you for sharing the Unity version info!

> And how could I disable the SSGI on the reflection camera?

A quick way is to create **another URP renderer without the SSGI renderer feature** (ex. "URP-HighFidelity-Renderer-2") and assign it to the reflection camera.

Another way is to use the camera's [**volume mask**](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@14.0/manual/camera-component-reference.html#Environment:~:text=the%20Render%20Pipeline.-,Volume%C2%A0Mask,-Use%20the%20drop) to define which URP volumes affect your reflection camera.

**Comment by Shandy666** [comment]
Using another URP renderer without SSGI render Feature is works perfectly and the easiest solution, thanks a lot for the solution. I will close this issue to let other peoples who facing the same problem know that the problem is solved. And by the way another thanks for your time.

Cheers
