### ISSUE TITLE
Lighting settings not taken into account

### ISSUE THREAD

**Issue by Poppedri** [jiaozi158/UnitySSGIURP#3]
Hi! One problem I've noticed with SSGI is that the lighting settings for a scene don't seem to work with it enabled.
In my scene, the Environment light and shadows is set to a mostly blue color using gradient:
![image](https://github.com/user-attachments/assets/b78a07cc-7d39-478a-a1cb-0cf2783a5da4)

However, with SSGI enabled, this seems to default to the standard black/grey lighting:
![image](https://github.com/user-attachments/assets/df106770-c0dc-4491-912d-4aedd2dee3da)

**Comment by Poppedri** [comment]
Nevermind, this was my fault. The option to fix this was in the Renderer Feature. I was looking through the Post Processing settings and could not find anything.

**Comment by jiaozi158** [comment]
Hi, glad to hear that you solved this issue!

I haven't started working on the documentation yet, so there might be some confusion.

Depending on the project type (ex. stylized, realistic, ...), the recommended setup can be different, which I'll mention in the documentation.
