### ISSUE TITLE
Unity 6000.0.4f1 - No effect unless Rendering Debugger option true

### ISSUE THREAD

**Issue by LunarHackett003** [jiaozi158/UnitySSGIURP#6]
The Renderer Feature seems to do nothing unless the Rendering Debugger option is enabled. Turning this on seems to give the expected results

**Comment by jiaozi158** [comment]
Hi, do you have any Rendering Debugger windows open in the project?

By default, SSGI is disabled to avoid affecting the lighting and rendering visualizations when using the Rendering Debugger.

The [SRP Runtime Frame Stats Panel](https://portal.productboard.com/unity/1-unity-platform-rendering-visual-effects/c/1435-srp-runtime-frame-stats-profiler-panel) is also a Rendering Debugger window.
![SRP Runtime Panel](https://github.com/user-attachments/assets/ad78deaf-9ee0-48f3-b47e-3a2b64976ab3)

**Comment by LunarHackett003** [comment]
Hi, thanks, I've just realised I still had the rendering debugger panel docked
